# Dockerfile for FastAPI
FROM python:3.9-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Install required packages
COPY requirements.txt ./tmp/
RUN pip install --no-cache-dir -r ./tmp/requirements.txt

# Copy your FastAPI app code to the container
COPY ./ /app
COPY .env /app/.env

# Set the working directory
WORKDIR /app

# Expose the port (optional)
EXPOSE 8000

# Run FastAPI using uvicorn
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]